from typing import List, Union

class BDD:
    false_: BDD
    true_: BDD
    null: BDD

    def __init__(self, val: int = 0) -> None: ...
    @staticmethod
    def var(v: int) -> BDD: ...
    @staticmethod
    def ite(f: BDD, g: BDD, h: BDD) -> BDD: ...
    @staticmethod
    def import_str(s: str) -> BDD: ...
    @staticmethod
    def import_file(path: str) -> BDD: ...

    def __and__(self, other: BDD) -> BDD: ...
    def __or__(self, other: BDD) -> BDD: ...
    def __xor__(self, other: BDD) -> BDD: ...
    def __invert__(self) -> BDD: ...
    def __lshift__(self, shift: int) -> BDD: ...
    def __rshift__(self, shift: int) -> BDD: ...
    def __iand__(self, other: BDD) -> BDD: ...
    def __ior__(self, other: BDD) -> BDD: ...
    def __ixor__(self, other: BDD) -> BDD: ...
    def __ilshift__(self, shift: int) -> BDD: ...
    def __irshift__(self, shift: int) -> BDD: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...

    def at0(self, v: int) -> BDD: ...
    def at1(self, v: int) -> BDD: ...
    def cofactor(self, g: BDD) -> BDD: ...
    def support(self) -> BDD: ...
    def support_vec(self) -> List[int]: ...
    def imply(self, other: BDD) -> int: ...
    def exist(self, cube_or_vars_or_var: Union[BDD, List[int], int]) -> BDD: ...
    def univ(self, cube_or_vars_or_var: Union[BDD, List[int], int]) -> BDD: ...
    def export_str(self) -> str: ...
    def export_file(self, path: str) -> None: ...

    @property
    def size(self) -> int: ...
    @property
    def top_var(self) -> int: ...
    @property
    def node_id(self) -> int: ...


class ZDD:
    empty: ZDD
    single: ZDD
    null: ZDD

    def __init__(self, val: int = 0) -> None: ...
    @staticmethod
    def import_str(s: str) -> ZDD: ...
    @staticmethod
    def import_file(path: str) -> ZDD: ...

    def __add__(self, other: ZDD) -> ZDD: ...
    def __sub__(self, other: ZDD) -> ZDD: ...
    def __and__(self, other: ZDD) -> ZDD: ...
    def __xor__(self, other: ZDD) -> ZDD: ...
    def __mul__(self, other: ZDD) -> ZDD: ...
    def __truediv__(self, other: ZDD) -> ZDD: ...
    def __mod__(self, other: ZDD) -> ZDD: ...
    def __iadd__(self, other: ZDD) -> ZDD: ...
    def __isub__(self, other: ZDD) -> ZDD: ...
    def __iand__(self, other: ZDD) -> ZDD: ...
    def __ixor__(self, other: ZDD) -> ZDD: ...
    def __imul__(self, other: ZDD) -> ZDD: ...
    def __itruediv__(self, other: ZDD) -> ZDD: ...
    def __imod__(self, other: ZDD) -> ZDD: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...

    def change(self, v: int) -> ZDD: ...
    def offset(self, v: int) -> ZDD: ...
    def onset(self, v: int) -> ZDD: ...
    def onset0(self, v: int) -> ZDD: ...
    def maximal(self) -> ZDD: ...
    def minimal(self) -> ZDD: ...
    def minhit(self) -> ZDD: ...
    def closure(self) -> ZDD: ...
    def restrict(self, g: ZDD) -> ZDD: ...
    def permit(self, g: ZDD) -> ZDD: ...
    def nonsup(self, g: ZDD) -> ZDD: ...
    def nonsub(self, g: ZDD) -> ZDD: ...
    def disjoin(self, g: ZDD) -> ZDD: ...
    def jointjoin(self, g: ZDD) -> ZDD: ...
    def delta(self, g: ZDD) -> ZDD: ...
    def export_str(self) -> str: ...
    def export_file(self, path: str) -> None: ...

    @property
    def card(self) -> int: ...
    @property
    def top_var(self) -> int: ...
    @property
    def node_id(self) -> int: ...


def init(node_count: int = 256, node_max: int = ...) -> None: ...
def newvar() -> int: ...
def newvar_of_level(lev: int) -> int: ...
def level_of_var(var: int) -> int: ...
def var_of_level(level: int) -> int: ...
def var_count() -> int: ...
def gc() -> None: ...
def live_nodes() -> int: ...
def gc_set_threshold(threshold: float) -> None: ...
def gc_get_threshold() -> float: ...
def node_count() -> int: ...
